"""Constants + env-driven config for the Apis worker.

Environment variables (all optional; defaults match the W1 devnet demo):
  APIS_RPC_HTTP    — HTTP endpoint for one-shot RPC calls (e.g. account
                     fetches). Default: public devnet.
  APIS_RPC_WS      — WebSocket endpoint for log subscriptions. Default:
                     public devnet. Swap to a Helius enhanced URL for
                     production volume.
  APIS_PROGRAM_ID  — apis_program address. Default: the devnet deployment
                     recorded in MEMORY.md (Step 5 close, 2026-05-09).
"""

import os
from pathlib import Path

RPC_HTTP_URL: str = os.environ.get("APIS_RPC_HTTP", "https://api.devnet.solana.com")
RPC_WS_URL: str = os.environ.get("APIS_RPC_WS", "wss://api.devnet.solana.com")

APIS_PROGRAM_ID: str = os.environ.get(
    "APIS_PROGRAM_ID", "2qe8YXciSpony5vjwxZAYJZ7WfRzSHKRdRzSiH868mhf"
)

# IDL is generated by `anchor build` in packages/program. We read it at
# startup to pull the event discriminators — that way the worker stays in
# sync with the program if event names/order change after a redeploy.
_PKG_ROOT: Path = Path(__file__).resolve().parent.parent
IDL_PATH: Path = _PKG_ROOT.parent / "program" / "target" / "idl" / "apis_program.json"
