// Agent wallet loader — Sprint 4.0a.
//
// The agent holds its own Solana keypair (separate from worker.json
// and the deployer keypair). Path defaults to ~/.config/apis/agent.json;
// override with APIS_AGENT_KEYPAIR. Generated by the bootstrap script
// `pnpm --filter agent buy --bootstrap-wallet` on first run.
//
// Per AGENTS.md the AI never *handles* the bytes — solders / solana-kit
// loads them locally, signs locally, returns a Signer wrapper. The
// keypair file itself stays at mode 0600 on disk; nothing in this
// module persists or transmits the raw bytes.

import {
  createKeyPairSignerFromBytes,
  type KeyPairSigner,
  type Address,
} from "@solana/kit";
import { existsSync, readFileSync, writeFileSync, chmodSync, mkdirSync } from "node:fs";
import { homedir } from "node:os";
import { dirname, resolve } from "node:path";
import { generateKeyPairSigner } from "@solana/kit";

const DEFAULT_PATH = resolve(homedir(), ".config", "apis", "agent.json");

export type AgentWallet = {
  signer: KeyPairSigner;
  address: Address;
  path: string;
};

export function agentKeypairPath(): string {
  return process.env.APIS_AGENT_KEYPAIR ?? DEFAULT_PATH;
}

/** Load the agent's keypair from disk. Throws if the file is missing
 *  — callers should fall back to `bootstrapAgentWallet()` and tell
 *  the user to fund the new pubkey. */
export async function loadAgentWallet(path?: string): Promise<AgentWallet> {
  const p = path ?? agentKeypairPath();
  if (!existsSync(p)) {
    throw new Error(
      `agent keypair not found at ${p}\n` +
        `→ run "pnpm --filter agent buy --bootstrap-wallet" to create one`,
    );
  }
  const raw = readFileSync(p, "utf-8");
  let bytes: Uint8Array;
  try {
    const arr = JSON.parse(raw) as number[];
    if (!Array.isArray(arr) || arr.length !== 64) {
      throw new Error(`keypair file is not a 64-element JSON array`);
    }
    bytes = new Uint8Array(arr);
  } catch (err) {
    throw new Error(
      `couldn't parse ${p}: ${err instanceof Error ? err.message : err}`,
    );
  }
  const signer = await createKeyPairSignerFromBytes(bytes);
  return { signer, address: signer.address, path: p };
}

/** Generate + persist a fresh agent keypair at the default path
 *  (mode 0600). Returns the pubkey so the caller can prompt the user
 *  to fund it before retrying. */
export async function bootstrapAgentWallet(
  path?: string,
): Promise<{ address: Address; path: string }> {
  const p = path ?? agentKeypairPath();
  if (existsSync(p)) {
    throw new Error(
      `keypair already exists at ${p} — refusing to overwrite. ` +
        `Delete the file manually if you really want a fresh one.`,
    );
  }
  mkdirSync(dirname(p), { recursive: true });
  const signer = await generateKeyPairSigner();
  // Re-extract the secret bytes via the SubtleCrypto export path used
  // internally by @solana/kit. As of v6 the cleanest way is to use the
  // signer's `keyPair.privateKey` and export both halves.
  // Simpler: use Web Crypto directly to round-trip the secret material.
  const exported = await exportSignerBytes(signer);
  writeFileSync(p, JSON.stringify(Array.from(exported)));
  chmodSync(p, 0o600);
  return { address: signer.address, path: p };
}

/** Export a KeyPairSigner's 64-byte secret-key form (32 bytes
 *  private + 32 bytes public) — matches the Solana CLI's id.json
 *  layout. We round-trip through SubtleCrypto since `@solana/kit`
 *  doesn't expose the bytes directly on the signer interface. */
async function exportSignerBytes(signer: KeyPairSigner): Promise<Uint8Array> {
  const priv = await crypto.subtle.exportKey("pkcs8", signer.keyPair.privateKey);
  const pub = await crypto.subtle.exportKey("raw", signer.keyPair.publicKey);
  // PKCS8 wraps the 32-byte Ed25519 seed inside an ASN.1 envelope; the
  // raw seed is the last 32 bytes.
  const privBytes = new Uint8Array(priv).slice(-32);
  const pubBytes = new Uint8Array(pub);
  const out = new Uint8Array(64);
  out.set(privBytes, 0);
  out.set(pubBytes, 32);
  return out;
}
