// Agent wallet loader — Sprint 4.0a.
//
// The agent holds its own Solana keypair (separate from worker.json
// and the deployer keypair). Path defaults to ~/.config/apis/agent.json;
// override with APIS_AGENT_KEYPAIR. Generated by the bootstrap script
// `pnpm --filter agent buy --bootstrap-wallet` on first run.
//
// Per AGENTS.md the AI never *handles* the bytes — solders / solana-kit
// loads them locally, signs locally, returns a Signer wrapper. The
// keypair file itself stays at mode 0600 on disk; nothing in this
// module persists or transmits the raw bytes.

import {
  createKeyPairSignerFromBytes,
  type KeyPairSigner,
  type Address,
} from "@solana/kit";
import {
  existsSync,
  readFileSync,
  writeFileSync,
  chmodSync,
  mkdirSync,
} from "node:fs";
import { generateKeyPairSync } from "node:crypto";
import { homedir } from "node:os";
import { dirname, resolve } from "node:path";

const DEFAULT_PATH = resolve(homedir(), ".config", "apis", "agent.json");

export type AgentWallet = {
  signer: KeyPairSigner;
  address: Address;
  path: string;
};

export function agentKeypairPath(): string {
  return process.env.APIS_AGENT_KEYPAIR ?? DEFAULT_PATH;
}

/** Load the agent's keypair from disk. Throws if the file is missing
 *  — callers should fall back to `bootstrapAgentWallet()` and tell
 *  the user to fund the new pubkey. */
export async function loadAgentWallet(path?: string): Promise<AgentWallet> {
  const p = path ?? agentKeypairPath();
  if (!existsSync(p)) {
    throw new Error(
      `agent keypair not found at ${p}\n` +
        `→ run "pnpm --filter agent buy --bootstrap-wallet" to create one`,
    );
  }
  const raw = readFileSync(p, "utf-8");
  let bytes: Uint8Array;
  try {
    const arr = JSON.parse(raw) as number[];
    if (!Array.isArray(arr) || arr.length !== 64) {
      throw new Error(`keypair file is not a 64-element JSON array`);
    }
    bytes = new Uint8Array(arr);
  } catch (err) {
    throw new Error(
      `couldn't parse ${p}: ${err instanceof Error ? err.message : err}`,
    );
  }
  const signer = await createKeyPairSignerFromBytes(bytes);
  return { signer, address: signer.address, path: p };
}

/** Generate + persist a fresh agent keypair at the default path
 *  (mode 0600). Returns the pubkey so the caller can prompt the user
 *  to fund it before retrying.
 *
 *  We use Node's native ed25519 keygen (extractable keys by default)
 *  rather than @solana/kit's `generateKeyPairSigner` — the latter
 *  produces SubtleCrypto keys with `extractable: false`, which means
 *  we can't write them back to disk in Solana's CLI format. */
export async function bootstrapAgentWallet(
  path?: string,
): Promise<{ address: Address; path: string }> {
  const p = path ?? agentKeypairPath();
  if (existsSync(p)) {
    throw new Error(
      `keypair already exists at ${p} — refusing to overwrite. ` +
        `Delete the file manually if you really want a fresh one.`,
    );
  }
  mkdirSync(dirname(p), { recursive: true });

  // Node 22+ supports synchronous ed25519 keygen. Export as DER and
  // pull out the raw 32-byte seed + 32-byte pubkey.
  const { publicKey, privateKey } = generateKeyPairSync("ed25519");
  const privDer = privateKey.export({ format: "der", type: "pkcs8" });
  const pubDer = publicKey.export({ format: "der", type: "spki" });
  // PKCS8 wraps the seed in an ASN.1 envelope; the seed is the last
  // 32 bytes. Same for SPKI (raw pubkey is the trailing 32 bytes).
  const privBytes = new Uint8Array(privDer).slice(-32);
  const pubBytes = new Uint8Array(pubDer).slice(-32);
  const full = new Uint8Array(64);
  full.set(privBytes, 0);
  full.set(pubBytes, 32);

  writeFileSync(p, JSON.stringify(Array.from(full)));
  chmodSync(p, 0o600);

  // Round-trip through createKeyPairSignerFromBytes to validate the
  // file we just wrote is loadable. Throws if the export was malformed.
  const signer = await createKeyPairSignerFromBytes(full);
  return { address: signer.address, path: p };
}
